#!/bin/bash
#SBATCH --partition=gpu_a100
#SBATCH --gpus-per-task=1
#SBATCH --job-name=FitDeepLearning
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=03:00:00
#SBATCH --output=slurm_fit_dl_%A.out
# Snellius: train the deep learning model (GPU).
# Submit with: sbatch fit_deeplearning.job

module purge
module load 2025
module load Anaconda3/2025.06-1

eval "$(conda shell.bash hook)"
conda activate dl_gpu

cd "$HOME/MAM09A2"
python src/models/fit_deeplearning.py --modeltype "CNN" --epochs 40
# change fit_deeplearning.py for hyperparameter_search.py to perform a hyperparameter search instead of training a single model.
