#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=FitDeep
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=02:00:00
#SBATCH --output=snelliusoutputs/slurm_fitdeeplearning_%A.out

# Clean environment and load modules
module purge
module load 2025
module load Anaconda3/2025.06-1

# Activate your environment (the one that has medmnist installed)
eval "$(conda shell.bash hook)"
conda activate dl2025

# Go to your project directory
cd $HOME/MAM09A2

# Run your script
python src/models/fit_deeplearning.py --modeltype "CNN" --epochs 40 